export enum SubwayStationEnumType {
  nevermind = 'Любая',
  red = 'Красная',
  green = 'Зеленая',
  blue = 'Синяя',
  lightBlue = 'Голубая',
  ring = 'Кольцевая',
  orange = 'Оранжевая',
  purple = 'Фиолетовая',
  yellow = 'Желтая',
  grey = 'Серая',
  lightGreen = 'Салатовая',
  lightPurple = 'Бирюзовая',
  greyBlue = 'Серо-голубая',
}
