version: '3.7'

services:
  backend:
    env_file:
      - .env
    networks:
      - web
    depends_on:
      - redis

  nginx:
    image: nginx
    networks:
      - web
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always

  redis:
    image: redis:6.2.6-alpine
    networks:
      - web
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

networks:
  web:
volumes:
  redis_data:
