version: '3.7'

services:
  backend:
    env_file:
      - .env
    networks:
      - web

  nginx:
    image: nginx
    networks:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    restart: always

  redis:
    image: redis:6.2.6-alpine
    networks:
      - web
    volumes:
      - redis_data:/data

networks:
  web:
volumes:
  redis_data:
