version: '3.7'

services:
  backend:
    container_name: backend_local
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
      - /app/node_modules
    command: "npm run start:debug:webstorm"
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres

  nginx:
    volumes:
      - ./data/nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf/:ro

  postgres:
    container_name: postgres_local
    image: postgres:13
    networks:
      - web
    environment:
      POSTGRES_PASSWORD: xiagn17homie
      POSTGRES_USER: xiagn17
      POSTGRES_DB: homie_db
      PGDATA: /data/pgdata
    volumes:
      - pgdata:/data/pgdata
    ports:
      - 5432:5432
    restart: unless-stopped

  redis:
    ports:
      - 6379:6379

volumes:
  pgdata:
