apiVersion: apps/v1
kind: Deployment
metadata:
  name: homie-deployment
  labels:
    env: prod
    app: homie-api-deploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: homie-api
  template:
    metadata:
      labels:
        app: homie-api
    spec:
      containers:
        - name: container-backend
          image: eu.gcr.io/homie-cloud-app/homie-bot-backend:0.13
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USERNAME
                  name: homie-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: homie-secret
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DATABASE
                  name: homie-secret
            - name: POSTGRES_HOST
              value: "34.116.135.35"
            - name: POSTGRES_PORT
              value: "5432"
            - name: TYPEORM_SYNCHRONIZE
              value: "false"
            - name: TYPEORM_LOGGING
              value: "true"
            - name: TYPEORM_MIGRATIONS_RUN
              value: "true"
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TELEGRAM_TOKEN
                  name: homie-secret
            - name: SENDPULSE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: SENDPULSE_CLIENT_ID
                  name: homie-secret
            - name: SENDPULSE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: SENDPULSE_CLIENT_SECRET
                  name: homie-secret
            - name: TRIAL_FREE_MATCHES_COUNT
              value: "3"
            - name: PAID_MATCHES_COUNT
              value: "2"
          resources:
            requests:
              memory: "304Mi"
              cpu: "140m"
            limits:
              memory: "576Mi"
              cpu: "381m"
