apiVersion: apps/v1
kind: Deployment
metadata:
  name: homie-deployment
  labels:
    env: prod
    app: homie-api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homie-api
  template:
    metadata:
      labels:
        app: homie-api
    spec:
      containers:
        - name: container-backend
          image: eu.gcr.io/homie-cloud-app/homie-bot-backend:0.11
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: POSTGRES_USERNAME
              value: "xiagn17"
            - name: POSTGRES_PASSWORD
              value: "xiagn17homie"
            - name: POSTGRES_DATABASE
              value: "homie_db"
            - name: POSTGRES_HOST
              value: "10.76.4.242"
            - name: POSTGRES_PORT
              value: "5432"
            - name: TYPEORM_SYNCHRONIZE
              value: "false"
            - name: TYPEORM_LOGGING
              value: "true"
            - name: TYPEORM_MIGRATIONS_RUN
              value: "true"
            - name: TELEGRAM_TOKEN
              value: "1996984517:AAFavrE0pzX5TCdUsx1gmkIsg-8QEy9TNKM"
            - name: SENDPULSE_CLIENT_ID
              value: "a067f09218be3a67a082a89412489667"
            - name: SENDPULSE_CLIENT_SECRET
              value: "5a87878e3ca511c655e3656e77eaf9c0"
            - name: TRIAL_FREE_MATCHES_COUNT
              value: "3"
            - name: PAID_MATCHES_COUNT
              value: "2"
          resources:
            requests:
              memory: "240Mi"
              cpu: "90m"
            limits:
              memory: "384Mi"
              cpu: "256m"
